export const userTexts = [
  ["salut", "hé", "bonjour", "bonjour", "bon après-midi", "bonne journée"],
  [
    "comment vas-tu",
    "Comment est la vie",
    "comment ça va",
    "comment allez-vous",
    "Tu vas bien",
    "êtes-vous bien",
    "comment se passe ta journée",
    "comment se passe ta journée",
    "quoi de neuf",
    "quoi de neuf",
    "tu es bon",
  ],
  [
    "que fais-tu",
    "que se passe-t-il",
    "qu'est-ce qui se passe",
    "quoi de neuf",
    "quoi de neuf",
    "tu es bon",
  ],
  [
    "comment se passe ta journée",
    "comment s'est passée ta journée",
    "Comment s'est passée ta journée",
    "comment se passe ta journée",
    "comment est ta journée",
    "comment est ta journée",
    "comment se passe ta journée",
    "comment se passe ta journée",
  ],
  ["quel âge as-tu", "es-tu vieux"],
  [
    "qui es-tu",
    "êtes-vous humain",
    "êtes-vous un robot",
    "êtes-vous un humain ou un robot",
  ],
  ["qui t'a créé", "qui t'a fait", "as-tu été créé"],
  [
    "votre nom s'il vous plait",
    "votre nom",
    "puis-je connaître ton nom",
    "quel est ton nom",
    "Comment t'appelles-tu",
    "Comment t'appelles-tu",
    "Qu'est-ce que je vous appelle",
    "As-tu un nom",
    "dis-moi ton nom",
  ],
];

export const botReplies = [
  ["Bonjour !", "Salut !", "Hé !", "Salut !", "Salut"],
  ["Bien et toi?", "Plutôt bien, et vous ?", "Fantastique, et toi ?"],
  [
    "Pas grand chose",
    "Sur le point d'aller dormir",
    "Je me détends juste",
    "Je ne sais pas en fait",
  ],
  ["Ça a été bien jusqu'à présent"],
  ["Je suis infini"],
  ["Je ne suis qu'un robot", "Je suis un robot. Qu'est-ce que tu es ?"],
  ["Le seul vrai Dieu, JavaScript"],
  ["Je suis sans nom", "Je n'ai pas de nom"],
  ["Je t'aime aussi", "Moi aussi"],
  ["Vous êtes-vous déjà senti mal ?", "Heureux de l'entendre"],
  [
    "Pourquoi ?",
    "Pourquoi ? Vous ne devriez pas !",
    "Essayez de regarder la télévision",
  ],
  ["Et alors ?", "Il était une fois... c'est la fin de mon histoire"],
  ["Raconte-moi une histoire", "Raconte-moi une blague", "Parle-moi de toi"],
  ["Au revoir", "Au revoir", "À plus tard"],
  ["Sushis", "Pizzas"],
  ["Frère!"],
  ["Excellente question"],
  ["C'est bon", "Je comprends", "De quoi veux-tu parler ?"],
  ["S'il te plait dis quelque chose :("],
  ["Haha !", "Bien!"],
  ["c'est bien", "c'est bien", "bien", "d'accord"],
];

export const alternative = [
  "Même",
  "Continue...",
  "Frère...",
  "Essayer à nouveau",
  "J'écoute...",
  "Je ne comprends pas :...",
];
